version: '3.9'
services:
  #PHP Service
  schedule:
    build:
      context: .
    restart: always
    ports:
      - "8110:8000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
